spring:
  application:
    name: WebRiseTest
  flyway:
    enabled: true
    baseline-on-migrate: true
  datasource:
    url: jdbc:postgresql://${datasource_url}/${datasource_database_name}
    username: ${datasource_username}
    password: ${datasource_password}
    driver-class-name: org.postgresql.Driver